# netlify.toml

[build]
  command = "npm run build"  # This tells Netlify to run `npm run build` for each deployment
  publish = "dist"         

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
